const generateSalesReport = require("../utils/salesReportService");
const ExcelJS = require("exceljs");
const PDFDocument = require("pdfkit");


exports.getSalesReport = async (req, res) => {
  try {
    const data=await generateSalesReport(req.body);
     return res.status(200).json({ success: true,message:"Sales report summary fetched successfully", data });
  } catch (error) {
    console.error("Error fetching sales report:", error);
    return res.status(500).json({ success: false, message: error.message });
  }
};




exports.downloadSalesPDF = async (req, res) => {
  try {
    const data = await generateSalesReport(req.body);

    const doc = new PDFDocument({
      size: "A4",
      margin: 50
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=sales_report.pdf");

    doc.pipe(res);

    // ---------------------------
    // Header
    // ---------------------------
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("Sales Report", { align: "center" });
    
    doc
      .moveDown(0.5)
      .fontSize(12)
      .font("Helvetica")
      .text(`Generated On: ${new Date().toLocaleString()}`, { align: "center" });

    doc.moveDown(1.5);

    // Divider
    doc
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke();

    doc.moveDown(1);

    // ---------------------------
    // Date Range Section
    // ---------------------------
    doc.fontSize(14).font("Helvetica-Bold").text("Date Range", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).font("Helvetica");
    doc.text(`Start Date: ${data.startDate}`);
    doc.text(`End Date: ${data.endDate}`);

    doc.moveDown(1);

    // Divider
    doc
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke();

    doc.moveDown(1);

    // ---------------------------
    // Overall Summary
    // ---------------------------
    doc.fontSize(14).font("Helvetica-Bold").text("Overall Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).font("Helvetica");
    doc.text(`Total Orders: ${data.totalOrders}`);
    doc.text(`Total Revenue: ₹${data.totalAmount}`);
    doc.text(`Total Discount: ₹${data.totalDiscount}`);
    doc.text(`Coupon Deduction: ₹${data.couponDeduction}`);

    doc.moveDown(1);

    // Divider
    doc
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke();

    doc.moveDown(1);

    // ---------------------------
    // Order Status Breakdown (Table Style)
    // ---------------------------
    doc.fontSize(14).font("Helvetica-Bold").text("Order Status Breakdown", { underline: true });
    doc.moveDown(0.7);

    // Table Header
    doc.fontSize(12).font("Helvetica-Bold");
    doc.text("Status", 60, doc.y);
    doc.text("Count", 400, doc.y);

    // Line below header
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.3);

    // Table Rows
    doc.font("Helvetica");
    const rows = [
      ["Delivered", data.delivered],
      ["Cancelled", data.cancelled],
      ["Shipped", data.shipped],
      ["Returned", data.returned],
      ["Pending", data.pending],
      ["Processing", data.processing],
    ];

    rows.forEach(([label, value]) => {
      doc.text(label, 60, doc.y);
      doc.text(String(value), 400, doc.y);
      doc.moveDown(0.4);
    });

    doc.moveDown(2);

    // ---------------------------
    // Footer
    // ---------------------------
    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by Admin Dashboard", 50, 780, { align: "center" });

    doc.end();

  } catch (err) {
    console.log(err);
    res.status(500).json({ success: false, message: err.message });
  }
};



