const generateSalesReport = require("../utils/salesReportService");
const ExcelJS = require("exceljs");
const PDFDocument = require("pdfkit");
const formatCurrency = require("../utils/formatCurrency");

exports.getSalesReport = async (req, res) => {
  try {
    const data = await generateSalesReport(req.body);
    return res
      .status(200)
      .json({
        success: true,
        message: "Sales report summary fetched successfully",
        data,
      });
  } catch (error) {
    console.error("Error fetching sales report:", error);
    return res.status(500).json({ success: false, message: error.message });
  }
};

exports.downloadSalesPDF = async (req, res) => {
  try {
    const data = await generateSalesReport(req.body);

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=sales_report.pdf"
    );

    doc.pipe(res);

    // ---------------------------
    // Header
    // ---------------------------
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("Sales Report", { align: "center" });

    doc
      .moveDown(0.5)
      .fontSize(12)
      .font("Helvetica")
      .text(`Generated On: ${new Date().toLocaleString()}`, {
        align: "center",
      });

    doc.moveDown(1.5);

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    doc.moveDown(1);

    // ---------------------------
    // Date Range Section
    // ---------------------------
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .text("Date Range", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).font("Helvetica");
    doc.text(`Start Date: ${data.startDate}`);
    doc.text(`End Date: ${data.endDate}`);

    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    doc.moveDown(1);

    // ---------------------------
    // Overall Summary
    // ---------------------------
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .text("Overall Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).font("Helvetica");
    doc.text(`Total Orders: ${data.totalOrders}`);
    doc.text(`Total Revenue:  ${formatCurrency(data.totalAmount)}`);
    doc.text(`Total Discount: ${formatCurrency(data.totalDiscount)}`);
    doc.text(`Coupon Deduction: ${formatCurrency(data.couponDeduction)}`);

    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    doc.moveDown(1);

    // ---------------------------
    // Order Status Breakdown (Table Style)
    // ---------------------------
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .text("Order Status Breakdown", { underline: true });
    doc.moveDown(0.7);

    // Table Header
    doc.fontSize(12).font("Helvetica-Bold");
    doc.text("Status", 60, doc.y);
    doc.text("Count", 400, doc.y);

    // Line below header
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.3);

    // Table Rows
    doc.font("Helvetica");
    const rows = [
      ["Delivered", data.delivered],
      ["Cancelled", data.cancelled],
      ["Shipped", data.shipped],
      ["Returned", data.returned],
      ["Pending", data.pending],
      ["Processing", data.processing],
    ];

    rows.forEach(([label, value]) => {
      doc.text(label, 60, doc.y);
      doc.text(String(value), 400, doc.y);
      doc.moveDown(0.4);
    });

    doc.moveDown(2);

    // ---------------------------
    // Footer
    // ---------------------------
    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by Admin Dashboard", 50, 780, { align: "center" });

    doc.end();
  } catch (err) {
    console.log(err);
    res.status(500).json({ success: false, message: err.message });
  }
};

exports.downloadSalesExcel = async (req, res) => {
  try {
    const data = await generateSalesReport(req.body);

    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet("Sales Report");

    // ---------- HEADER ----------
    sheet.mergeCells("A1", "B1");
    sheet.getCell("A1").value = "Sales Report";
    sheet.getCell("A1").font = { size: 18, bold: true };
    sheet.getCell("A1").alignment = { horizontal: "center" };

    sheet.addRow([]);
    sheet.addRow(["Generated On", new Date().toLocaleString()]);
    sheet.addRow([]);

    // ---------- DATE RANGE ----------
    sheet.addRow(["Start Date", data.startDate]);
    sheet.addRow(["End Date", data.endDate]);
    sheet.addRow([]);

    // ---------- SUMMARY ----------
    sheet.addRow(["Total Orders", data.totalOrders]);
    sheet.addRow(["Total Revenue", `₹${data.totalAmount}`]);
    sheet.addRow(["Total Discount", `₹${data.totalDiscount}`]);
    sheet.addRow(["Coupon Deduction", `₹${data.couponDeduction}`]);
    sheet.addRow([]);

    // ---------- STATUS TABLE ----------
    sheet.addRow(["Status", "Count"]).font = { bold: true };
    const rows = [
      ["Delivered", data.delivered],
      ["Cancelled", data.cancelled],
      ["Shipped", data.shipped],
      ["Returned", data.returned],
      ["Pending", data.pending],
      ["Processing", data.processing],
    ];
    sheet.addRows(rows);

    // Auto column width
    sheet.columns.forEach((col) => {
      col.width = 25;
    });

    // ---------- DOWNLOAD ----------
    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=sales_report.xlsx"
    );

    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};
